### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [2]:
import numpy as np
from numpy import random 

mat = random.randint(1, 10, size=(5, 5))
print(mat)
mat[0, :], mat[-1, :] = mat[-1, :].copy(), mat[0, :].copy()

print("\nAfter swapping")
print(mat)


[[8 4 8 8 4]
 [7 7 4 8 9]
 [6 3 1 7 5]
 [8 4 4 6 4]
 [4 6 4 4 4]]

After swapping
[[4 6 4 4 4]
 [7 7 4 8 9]
 [6 3 1 7 5]
 [8 4 4 6 4]
 [8 4 8 8 4]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [15]:
arr = np.array([[1, 2, 3], [4, 0, 5], [6, 7, 8], [0,9,10 ]])
print(arr)

arr1 = arr[~np.any(arr == 0, axis=1)]
print("\nafter removing rows with zeros")
print(arr1)


[[ 1  2  3]
 [ 4  0  5]
 [ 6  7  8]
 [ 0  9 10]]

after removing rows with zeros
[[1 2 3]
 [6 7 8]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [28]:
arr = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])

rel_part = np.real(arr)
img_part = np.imag(arr)

print(arr)
print("\nreal part")
print(rel_part)
print("\nimaginary part")
print(img_part)


[1.        +0.j         0.70710678+0.70710678j]

real part
[1.         0.70710678]

imaginary part
[0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [29]:
arr = np.array([10, 10, 20, 20, 30, 30, 40])
arr1 = np.unique(arr)

print(arr)
print("\nafter removing duplicates")
print(arr1)


[10 10 20 20 30 30 40]

after removing duplicates
[10 20 30 40]


### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [49]:
arr = random.rand(3, 3, 3)
print(arr)


[[[0.03836133 0.94785348 0.63959493]
  [0.28946184 0.36989074 0.19838672]
  [0.61176728 0.01122217 0.36546626]]

 [[0.67967069 0.4818278  0.27445109]
  [0.82570384 0.65780895 0.41078466]
  [0.67873528 0.95608388 0.36168718]]

 [[0.65325761 0.09350142 0.84479837]
  [0.86194413 0.51209317 0.44456185]
  [0.35055041 0.50340394 0.76463629]]]


### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [27]:
arr = random.randint(2,20, size=(10))

print("\narr")
print(arr)

def sort(arr,n):
    for i in range(n):
        
        for j in range(n-i-1):
            
            if arr[j]>arr[j+1]:
                temp=arr[j]
                arr[j]=arr[j+1]
                arr[j+1]=temp
    return arr

n=len(arr)
arr1=sort(arr,n)

print("\nsorted arr")
print(arr1)



arr
[ 6 11 19  2 17  3  6 15  2 18]


TypeError: 'int' object is not callable

### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [34]:
arr1 = np.random.rand(3, 3)
arr2 = np.random.rand(3, 3)

check = np.array_equal(arr1,arr2)

print("\narr1")
print(arr1)
print("\narr2")
print(arr2)

if check:
    print("\narrays are equal")
else:
    print("\narrays are not equal")



arr1
[[0.63702949 0.30466696 0.67420131]
 [0.39136156 0.83803678 0.60418637]
 [0.71434862 0.30831558 0.24668438]]

arr2
[[0.06151833 0.85579712 0.36511977]
 [0.58903925 0.29412463 0.00360142]
 [0.75734399 0.91458361 0.06532286]]

arrays are not equal


### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [43]:
arr = np.array([[10, 40], [30, 20]])

first_axis = np.sort(arr, axis=0)
last_axis = np.sort(arr, axis=-1)
flatened = np.sort(arr.flatten())

print("\nfirst axis")
print(first_axis)

print("\nlast axis")
print(last_axis)

print("\nflattened")
print(flatened.reshape(arr.shape))


first axis
[[10 20]
 [30 40]]

last axis
[[10 40]
 [20 30]]

flattened
[[10 20]
 [30 40]]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [41]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.])

print("\nfloor")
print(np.floor(x))

print("\nceil")
print(np.ceil(x))

print("\ntruncate")
print(np.trunc(x)) 



floor
[-2. -2. -1.  0.  1.  1.  2.]

ceil
[-1. -1. -0.  1.  2.  2.  2.]

truncate
[-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [57]:
x= np.arange('2017-03', '2017-04', dtype='datetime64[D]')
print(x)


['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [73]:
import datetime
arr = np.empty(())
start = datetime.datetime(2023, 1, 1)
for i in range(24):
    arr = start + datetime.timedelta(hours=i)
    print(arr)

2023-01-01 00:00:00
2023-01-01 01:00:00
2023-01-01 02:00:00
2023-01-01 03:00:00
2023-01-01 04:00:00
2023-01-01 05:00:00
2023-01-01 06:00:00
2023-01-01 07:00:00
2023-01-01 08:00:00
2023-01-01 09:00:00
2023-01-01 10:00:00
2023-01-01 11:00:00
2023-01-01 12:00:00
2023-01-01 13:00:00
2023-01-01 14:00:00
2023-01-01 15:00:00
2023-01-01 16:00:00
2023-01-01 17:00:00
2023-01-01 18:00:00
2023-01-01 19:00:00
2023-01-01 20:00:00
2023-01-01 21:00:00
2023-01-01 22:00:00
2023-01-01 23:00:00


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [63]:
arr1 = np.array(['Python', 'PHP'], dtype=str)
arr2 = np.array([' Java', ' C++'], dtype=str)

print("\narr1")
print(arr1)

print("\narr2:")
print(arr2)

arr3 = np.char.add(arr1, arr2)

print("\narr3")
print(arr3)



arr1
['Python' 'PHP']

arr2:
[' Java' ' C++']

arr3
['Python Java' 'PHP C++']
